---
version: "2.1"
services:
  netbootxyz:
    container_name: netbootxyz
    build:
      context: .
    environment:
      - DHCP_RANGE_START=${SUBNET:-192.168.0.1}
    networks:
      netbootxyz_network:
        ipv4_address: ${CONTAINER_IP:-192.168.0.250}
    cap_add:
      - NET_ADMIN
networks:
  netbootxyz_network:
    driver: ipvlan
    driver_opts:
      parent: ${INTERFACE:-eth0}
    ipam:
      config:
        - subnet: ${SUBNET:-192.168.0.1}/${SUBNET_PREFIX_BITS:-24}
          gateway: ${GATEWAY:-192.168.0.1}
          ip_range: ${CONTAINER_IP:-192.168.0.250}/32
